// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKy2VRT3mA0IXbLvkyTp1V-VYTzINjJI',
    appId: '1:181198666084:web:dbb5c5499fc87deca1a271',
    messagingSenderId: '181198666084',
    projectId: 'vehiclerenewalnew',
    authDomain: 'vehiclerenewalnew.firebaseapp.com',
    storageBucket: 'vehiclerenewalnew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQXwmz6kJBHB35NJMZgmoL6TEJ1TsxaQ',
    appId: '1:181198666084:android:4043550825d55847a1a271',
    messagingSenderId: '181198666084',
    projectId: 'vehiclerenewalnew',
    storageBucket: 'vehiclerenewalnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfP4st6ryl-VALoYIrMs6Zarj4QV0emE',
    appId: '1:181198666084:ios:ab5f975e11c50db1a1a271',
    messagingSenderId: '181198666084',
    projectId: 'vehiclerenewalnew',
    storageBucket: 'vehiclerenewalnew.firebasestorage.app',
    iosBundleId: 'com.cretcom.vehiclerenewalNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfP4st6ryl-VALoYIrMs6Zarj4QV0emE',
    appId: '1:181198666084:ios:ab5f975e11c50db1a1a271',
    messagingSenderId: '181198666084',
    projectId: 'vehiclerenewalnew',
    storageBucket: 'vehiclerenewalnew.firebasestorage.app',
    iosBundleId: 'com.cretcom.vehiclerenewalNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEKy2VRT3mA0IXbLvkyTp1V-VYTzINjJI',
    appId: '1:181198666084:web:a147d4e8f58e5758a1a271',
    messagingSenderId: '181198666084',
    projectId: 'vehiclerenewalnew',
    authDomain: 'vehiclerenewalnew.firebaseapp.com',
    storageBucket: 'vehiclerenewalnew.firebasestorage.app',
  );
}
